spring:
  application:
    name: demo

  datasource:
    url: jdbc:h2:mem:demo-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true

hibernate:
  search:
    backend:
      type: lucene
      directory:
        type: local-heap
    schema_management:
      strategy: drop-and-create

dummyApi:
  users:
    url: https://dummyjson.com/users